[profile.dev]
panic = "abort" # Don't want panics since that will crash anyway

[profile.release]
panic = "abort"

[profile.lto]
panic = "abort"
codegen-units = 1 # Better optimization
debug = false # Inherits from release so should actually do nothing but whatever
inherits = "release"
lto = true # link time optimization
strip = true # smaller binary
