name: "Publish"
on:
  push:
    branches:
      - main
jobs:
  publish_prebuilt:
    strategy:
      matrix:
        platform: [
          { runner: ubuntu-20.04, target: x86_64-unknown-linux-gnu, output: libnvim_winpick.so, dest: nvim_winpick.so }, 
          { runner: ubuntu-22.04-arm, target: aarch64-unknown-linux-gnu, output: libnvim_winpick.so, dest: nvim_winpick.so },
          { runner: macos-latest, target: aarch64-apple-darwin, output: libnvim_winpick.dylib, dest: nvim_winpick.so } ]
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: build ${{ matrix.platform.target }}
        run: bash ${GITHUB_WORKSPACE}/.github/publish-prebuilt.sh ${{ matrix.platform.target }} ${{ matrix.platform.output }} ${{ matrix.platform.dest }} ${{ runner.temp }}

